### ISSUE TITLE
搭建过程中，镜像无法拉取

### ISSUE THREAD

**Issue by liunick2021** [WeBankFinTech/Prophecis#19]
有2个镜像无法拉取，一个是wedataspere/prophecis:minio-2020-06-14的镜像无法拉取；一个是wedatasphere/prophecis:fluent-bit-1.2.1的镜像 ，请问是否仓库当前是否存在该镜像？

**Comment by alexzyWu** [comment]
Hi，已重新上传，fluent-bit和minio都是用开源版本，直接使用开源镜像也是OK的。

**Comment by gugumituo** [comment]
您好！
wedatasphere/prophecis:metrics-0.2.0
wedatasphere/prophecis:jobmonitor-0.2.0
wedataspere/prophecis:minio-2020-06-14
wedatasphere/prophecis:lcm-0.2.0
wedatasphere/prophecis:trainer-0.2.0
这些镜像都无法拉取。
