### ISSUE TITLE
镜像无法拉取！！！

### ISSUE THREAD

**Issue by gugumituo** [WeBankFinTech/Prophecis#20]
您好！
wedatasphere/prophecis:metrics-0.2.0
wedatasphere/prophecis:jobmonitor-0.2.0
wedataspere/prophecis:minio-2020-06-14
wedatasphere/prophecis:lcm-0.2.0
wedatasphere/prophecis:trainer-0.2.0
这些镜像都无法拉取，请问仓库里有这些镜像吗？

**Comment by 15162766507** [comment]
这个项目镜像确实无法拉取，还有人维护这个开源项目吗

**Comment by monkey408** [comment]
我也遇到了相同的问题，请问有解决方法吗？？

**Comment by finalTestin** [comment]
镜像都已经重新上传了
