### ISSUE TITLE
创建notebook一直是waiting状态

### ISSUE THREAD

**Issue by marstalk** [WeBankFinTech/Prophecis#40]
- helm version：version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
- docker version: 
```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:24:05 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13
  GitCommit:        9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

-k8s version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

创建NoteBook之后，状态一直都是waiting，该如何处理？哪里能看到日志？

**Comment by marstalk** [comment]
我知道为什么一直在waiting状态了
因为我们在创建notebook的时候，需要选取使用具体哪一个镜像来创建，但是我查看日志发现，默认的基本备选镜像都已经不存在了：
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-2.0.0-jupyterlab-gpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.13.1-jupyterlab-cpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.13.1-jupyterlab-gpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.12.0-jupyterlab-gpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.12.0-jupyterlab-cpu-v0.5.0

镜像wedatasphere/prophecis的这几个tag都已经找不到了，是不是下线了？
https://hub.docker.com/r/wedatasphere/prophecis/tags?page=1

**Comment by marstalk** [comment]
我知道为什么一直在waiting状态了
因为我们在创建notebook的时候，需要选取使用具体哪一个镜像来创建，但是我查看日志发现，默认的基本备选镜像都已经不存在了：
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-2.0.0-jupyterlab-gpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.13.1-jupyterlab-cpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.13.1-jupyterlab-gpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.12.0-jupyterlab-gpu-v0.5.0
- wedatasphere/prophecis:MLSS-AIDE_1.8.0_tensorflow-1.12.0-jupyterlab-cpu-v0.5.0

镜像wedatasphere/prophecis的这几个tag都已经找不到了，是不是下线了？
https://hub.docker.com/r/wedatasphere/prophecis/tags?page=1

**Comment by wallyell** [comment]
看样子镜像确实下线了。配置做一些改动即可。
1. 在/install/Prophecis/values.yaml 中增加如下配置：
   
      ml_repository: wedatasphere/mllabis

2. 在/install/Prophecis/templates/ui/bdap-ui/bdap-ui-config.yml 中修改如下配置：
 'AIDE': {
                'defineImage': '{{.Values.server_repository}}',
                'imageOption': [{{range .Values.ui.aide.image.notebookTags}}'{{.name}}',{{end}}]
 },

改成：

 'AIDE': {
                'defineImage': '{{.Values.ml_repository}}',
                'imageOption': [{{range .Values.ui.aide.image.notebookTags}}'{{.name}}',{{end}}]
 },

主要修改内容在该文件192行中对应的镜像库地址

**Comment by wallyell** [comment]
另外需改动/install/Prophecis/values.yaml 中第63-67行对应的镜像tag配置，改成如下即可：
aide:
    image:
      notebookTags:
        - name: Prophecis_1.8.0_tensorflow-1.12.0-jupyterlab-cpu-v0.5
        - name: Prophecis_1.8.0_tensorflow-2.0.0-jupyterlab-gpu-v0.5.0

**Comment by marstalk** [comment]
通过这种方式已经成功的解决notebook waiting的问题，是不是可以提交一个PR把这些修改合并到主仓库中？

**Comment by wallyell** [comment]
近期会发布下一个版本，等看看他们的发布后的新版本再说吧。
